dist: trusty
sudo: false
language: java
jdk:
  - openjdk8

cache:
  directories:
  - $HOME/.m2

env:
  MAVEN_SKIP_RC=true
  MAVEN_OPTS="-Dmaven.repo.local=$HOME/.m2/repository -Xmx2g"

before_install:
  - cat ~/.m2/settings.xml
  - rm ~/.m2/settings.xml
