dist: trusty
sudo: false
language: java
jdk:
  - openjdk8
before_install:
  - rm ~/.m2/settings.xml
  - export MAVEN_SKIP_RC=true
  - export MAVEN_OPTS="-Dmaven.repo.local=$HOME/.m2/repository -Xmx2g"
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V --update-snapshots
  
